### ISSUE TITLE
Bundling failed: ReferenceError: ReactNativeRenderGenerator is not defined

### ISSUE THREAD

**Issue by ThePJMP** [GeekyAnts/vue-native-core#195]
After upgrading vue-native-core (from 0.0.8 to 0.1.2) & react-native version (from 0.55.4 to 0.59.8) bunding failed with following error: 

Bundling failed: ReferenceError: ReactNativeRenderGenerator is not defined

Compiling is failing on this line
https://github.com/GeekyAnts/vue-native-core/blob/b72b8ca0b184a3ce4caa7dc561a8ac659bae8b6a/src/compiler/parser/index.js#L552

After manually changing ReactNativeRenderGenerator to ReactNativeRenderGenerator$1 it says error: bundling failed: ReferenceError: _ is not defined

https://github.com/GeekyAnts/vue-native-core/blob/b72b8ca0b184a3ce4caa7dc561a8ac659bae8b6a/src/platforms/vue-native/compiler/native.js#L62

I fixed manually adding lodash, and it worked.

**Comment by jgiovanni** [comment]
I came across this same issue, and resolved it the same way, instead I replaced _.union with 
```
function union_arrays (x, y) {
  var obj = {};
  for (var i = x.length-1; i >= 0; -- i)
    obj[x[i]] = x[i];
  for (var i = y.length-1; i >= 0; -- i)
    obj[y[i]] = y[i];
  var res = []
  for (var k in obj) {
    if (obj.hasOwnProperty(k))  // <-- optional
      res.push(obj[k]);
  }
  return res;
}
```

**Comment by RishabhKarnad** [comment]
@ThePJMP did you also upgrade `vue-native-helper` and `vue-native-scripts`? The package versions should now always remain the same.

So use 
```
$ npm i --save vue-native-core@0.1.2 vue-native-helper@0.1.2
$ npm i --save-dev vue-native-scripts@0.1.2
```

**Comment by ThePJMP** [comment]
@RishabhKarnad yes. In fact, I'm working with 0.1.3 versions and still having this issue

**Comment by RishabhKarnad** [comment]
@ThePJMP It looks like this will only happen when using `render-prop` or `render-prop-fn`. We're working on it and we'll fix this in the next release (should be out in a few days)

**Comment by RishabhKarnad** [comment]
This issue has been fixed with release 0.1.4

https://github.com/GeekyAnts/vue-native-core/releases/tag/v0.1.4

**Comment by lucasromanojf** [comment]
Somehow vue-native-scripts is loading vue-native-template-compiler version 0.1.3 as dependency and not 0.1.4, and then the error still occurs here, unfortunately.

**Comment by ThePJMP** [comment]
> Somehow vue-native-scripts is loading vue-native-template-compiler version 0.1.3 as dependency and not 0.1.4, and then the error still occurs here, unfortunately.

You have to upgrade all your vue-native-* dependencies

I can confirm this issue was solved on version 0.1.4

**Comment by lucasromanojf** [comment]
I did this. Not sure what I am doing wrong.

**Comment by RishabhKarnad** [comment]
@lucasromanojf try deleting your `yarn.lock` or `package-lock.json` (whichever you are using) and node_modules/ and try reinstalling.

**Comment by lucasromanojf** [comment]
> @lucasromanojf try deleting your `yarn.lock` or `package-lock.json` (whichever you are using) and node_modules/ and try reinstalling.

Coincidentally I had to reinstall my OS, then I cloned the project, deleted the yarn.lock file, ran yarn install and it worked. Not sure if it was cache or the lock file before, but now it is working. Thank you very much!
