### ISSUE TITLE
Can't resolve '../../App' in node_modules/expo/AppEntry.js

### ISSUE THREAD

**Issue by loverg-c** [GeekyAnts/vue-native-core#235]
**Development platform:**
 - OS: Ubuntu 19.04
 - Shell: zsh 5.5.1 (x86_64-ubuntu-linux-gnu)
-  **yarn** 1.21.1
-  **vue-native** 0.1.1
- **expo** 3.13.1
 - Device: web browser (firefox 68.0.1 and chromium 80.0.3987.100)

**Repository to reproduce**
https://github.com/loverg-c/sample-vue-native

**Description of the bug**
I tried to initialize a completely new vue-native project with expo with the command : `vue-native init sample-vue-native` .
 It has generated the project, and I launched it with yarn start. When I try to run on web browser, I got this error : 
```
/home/clement/projects/vue/sample-vue-native/node_modules/expo/AppEntry.js
Module not found: Can't resolve '../../App' in '/home/clement/projects/vue/sample-vue-native/node_modules/expo'
```

I already have 'vue' in sourceExts in app.json [see here](https://github.com/loverg-c/sample-vue-native/blob/master/app.json)

**Comment by RishabhKarnad** [comment]
Hey @loverg-c this issue was fixed some time back. Have you tried updating `vue-native-cli`?

```
$yarn global add vue-native-cli@latest
```

**Comment by loverg-c** [comment]
Hello @RishabhKarnad ,

Yes I have the latest vue-native cli (v0.1.1) (I tried to reinstall it for trying but still the same problem), and yes it has generated the options in the app.json (you can see it on this preivous link: https://github.com/loverg-c/sample-vue-native/blob/master/app.json from lines 29 to 38)

**Comment by merencia** [comment]
Same problem here.
It looks a new version of issue #183 
I know vue, and I think that this could be a good way to create a mobile app.

So I've installed vue-cli:
`npm install --global vue-native-cli`
and expo:
`npm install --global expo-cli`
than I've created a new app:
`vue-native init app`
checked the sourceExts at `app.js` 
and run my new app on web
`npm run web`.

Than I got that:
```
my/app/path/node_modules/expo/AppEntry.js
Module not found: Can't resolve '../../App' in '/my/app/path/node_modules/expo'
```

I've user vue-native-cli verision 0.1.1 and this is my generated package.json with all versions:
```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^37.0.7",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "~0.11.7",
    "vue-native-core": "0.1.4",
    "vue-native-helper": "0.1.4"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-0",
    "babel-preset-expo": "~8.1.0",
    "vue-native-scripts": "0.1.4"
  },
  "private": true
}
```

**Comment by NikolaNikushev** [comment]
I confirm that I am having the same issue.

I just tried to update my existing project & also create a brand new one.
- Updated my expo & vue cli; 
- create the new project, 
the config is as @RishabhKarnad mentioned and should have been resolved, but the issue persists.

node@12.10
expo-cli@3.19.2
vue-native-cli@0.1.1

**Comment by GORobert** [comment]
Same issue here, fresh install of expo and vue-native

**Comment by Tanami** [comment]
same problem here, latest expo-cli, vue-native

**Comment by RishabhKarnad** [comment]
Hi everyone, in case you are trying to run on web, it won't work at the moment due to https://github.com/GeekyAnts/vue-native-cli/issues/37

That issue was moved to `vue-native-cli`, but this one got left behind.

I'm closing this issue, since it's a duplicate.

Please ONLY reopen if you are facing the issue on iOS/Android with vue-native-cli@^0.1.2 and latest Expo/RN CLI
